spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/e3mall    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    
    
mybatis:  mapper-locations: classpath:mapping/TbUserMapper.xml  config-location: classpath:mybatis/mybatis-config.xml
  
pagehelper:  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
    